// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.codingharbour.protobuf.user

@SerialVersionUID(0L)
final case class User(
    name: _root_.scala.Predef.String = "",
    favoriteNumber: _root_.scala.Long = 0L,
    favoriteColor: _root_.scala.Predef.String = ""
    ) extends scalapb.GeneratedMessage with scalapb.Message[User] with scalapb.lenses.Updatable[User] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = favoriteNumber
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(2, __value)
        }
      };
      
      {
        val __value = favoriteColor
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = favoriteNumber
        if (__v != 0L) {
          _output__.writeInt64(2, __v)
        }
      };
      {
        val __v = favoriteColor
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.codingharbour.protobuf.user.User = {
      var __name = this.name
      var __favoriteNumber = this.favoriteNumber
      var __favoriteColor = this.favoriteColor
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readString()
          case 16 =>
            __favoriteNumber = _input__.readInt64()
          case 26 =>
            __favoriteColor = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      com.codingharbour.protobuf.user.User(
          name = __name,
          favoriteNumber = __favoriteNumber,
          favoriteColor = __favoriteColor
      )
    }
    def withName(__v: _root_.scala.Predef.String): User = copy(name = __v)
    def withFavoriteNumber(__v: _root_.scala.Long): User = copy(favoriteNumber = __v)
    def withFavoriteColor(__v: _root_.scala.Predef.String): User = copy(favoriteColor = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = favoriteNumber
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = favoriteColor
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PLong(favoriteNumber)
        case 3 => _root_.scalapb.descriptors.PString(favoriteColor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.codingharbour.protobuf.user.User
}

object User extends scalapb.GeneratedMessageCompanion[com.codingharbour.protobuf.user.User] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.codingharbour.protobuf.user.User] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): com.codingharbour.protobuf.user.User = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.codingharbour.protobuf.user.User(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(1), 0L).asInstanceOf[_root_.scala.Long],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[_root_.scala.Predef.String]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.codingharbour.protobuf.user.User] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.codingharbour.protobuf.user.User(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = UserProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = UserProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.codingharbour.protobuf.user.User(
    name = "",
    favoriteNumber = 0L,
    favoriteColor = ""
  )
  implicit class UserLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.codingharbour.protobuf.user.User]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.codingharbour.protobuf.user.User](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def favoriteNumber: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.favoriteNumber)((c_, f_) => c_.copy(favoriteNumber = f_))
    def favoriteColor: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.favoriteColor)((c_, f_) => c_.copy(favoriteColor = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val FAVORITE_NUMBER_FIELD_NUMBER = 2
  final val FAVORITE_COLOR_FIELD_NUMBER = 3
  def of(
    name: _root_.scala.Predef.String,
    favoriteNumber: _root_.scala.Long,
    favoriteColor: _root_.scala.Predef.String
  ): _root_.com.codingharbour.protobuf.user.User = _root_.com.codingharbour.protobuf.user.User(
    name,
    favoriteNumber,
    favoriteColor
  )
}
