// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.codingharbour.protobuf.user

object UserProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.codingharbour.protobuf.user.User
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgp1c2VyLnByb3RvEhpjb20uY29kaW5naGFyYm91ci5wcm90b2J1ZiKeAQoEVXNlchIdCgRuYW1lGAEgASgJQgniPwYSBG5hb
  WVSBG5hbWUSPAoPZmF2b3JpdGVfbnVtYmVyGAIgASgDQhPiPxASDmZhdm9yaXRlTnVtYmVyUg5mYXZvcml0ZU51bWJlchI5Cg5mY
  XZvcml0ZV9jb2xvchgDIAEoCUIS4j8PEg1mYXZvcml0ZUNvbG9yUg1mYXZvcml0ZUNvbG9yQgxCClVzZXJEZXRhaWxiBnByb3RvM
  w=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}